---
title: "Stockton Green Economy Report"
author: "City Systems"
date: "Last Updated: February 2020"
output: 
  bookdown::gitbook:
    df_print: paged
    includes:
      in_header: header.html
    config:
      toc:
        collapse: none
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: null
      search: yes
      fontsettings:
        theme: white
        family: sans
        size: 2
      sharing:
        facebook: no
        github: no
        twitter: no
        linkedin: no
        weibo: no
        instapaper: no
        vk: no
        all: no
      info: no
editor_options: 
  chunk_output_type: console
---

# Test ADU

```{r}
library(censusapi)
library(tidyverse)
library(tigris)
library(sf)
library(mapview)
library(raster)
library(lwgeom)
library(smoothr)
library(lwgeom)
library(units)
library(geosphere)
library(tidytransit)
mapviewOptions(
  basemaps = "OpenStreetMap"
)
options(
  tigris_class = "sf",
  tigris_use_cache = TRUE
)
```

```{r}
projection <- "+proj=utm +zone=10 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=ft +no_defs"
```

```{r}
stockton_boundary_influence_projected <- st_read("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/SpheresOfInfluence/SpheresOfInfluence.shp", quiet = TRUE) %>% 
  filter(SPHERE == "STOCKTON") %>% 
  st_transform(projection) #stockton boundary is legit but really spotty, so i prefer using sphere of influence from the County GIS page.

# sjc_parcels <-
#   st_read("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/Parcels/Parcels.shp") %>%
#   st_transform(projection) %>%
#   st_make_valid()
# save(sjc_parcels, file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/Parcels/sjc_parcels.Rdata")
load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/Parcels/sjc_parcels.Rdata")

# stockton_parcels <-
#   sjc_parcels[stockton_boundary_influence_projected,]
# 
# stockton_parcels_extended <-
#   sjc_parcels[st_buffer(stockton_boundary_influence_projected,500),]
# save(stockton_parcels,stockton_parcels_extended,file="C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/Parcels/stockton_parcels.Rdata")
load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/Parcels/stockton_parcels.Rdata")

# sjc_zoning <-
#   st_read("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/Zoning/Zoning.shp") %>%
#   st_transform(projection) %>%
#   filter(ZNLABEL != "STOCKTON")
# 
# stockton_zoning <-
#   st_read("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/Stockton_Zoning/Zoning.shp") %>%
#   st_transform(projection)
```

```{r}
# load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ca_blocks_lite.Rdata")
# 
# stockton_blocks <- st_transform(ca_blocks_lite,projection)[stockton_boundary_influence_projected,]
#   
# save(stockton_blocks, file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/stockton_blocks.Rdata")
```

```{r}
load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/USBuildingFootprints/bldg_join.Rdata")

bldg_join <-
  bldg_join %>% 
  st_transform(projection)
```

```{r}
residential_bldg <-
  bldg_join %>% 
  filter(ZONING == "R")

stockton_residential_parcels <-
  stockton_parcels %>%
  filter(APN %in% residential_bldg$APN)
# some parcels are missing because there was no building footprint on the parcel even though it's a residential parcel. later, can come back and find those that did not get a building joined, and manually correct or identify as vacant
```

```{r}
# yard_setbacks <-
#   stockton_residential_parcels %>%
#   st_buffer(-4, joinStyle = "MITRE", mitreLimit = 1) # 4ft yard setback
# 
# house_setbacks <-
#   residential_bldg %>%
#   st_buffer(5, joinStyle = "MITRE", mitreLimit = 1) #5 ft house setback
# 
# adu_available_land <- NULL
# for(row in 1:floor(nrow(stockton_residential_parcels)/1000)){
# 
#   start <- row*1000-999
# 
#   end <- ifelse(
#     row < floor(nrow(stockton_residential_parcels)/1000),
#     row*1000,
#     nrow(stockton_residential_parcels)
#   )
# 
#   print(paste0(start," to ",end))
# 
#   available_land <-
#     st_difference(yard_setbacks[which(yard_setbacks$APN %in% stockton_residential_parcels$APN[start:end]),], st_union(house_setbacks[which(house_setbacks$APN %in% stockton_residential_parcels$APN[start:end]),]))
# 
#   adu_available_land <-
#     adu_available_land %>%
#     rbind(available_land)
# }
# save(adu_available_land, file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/adu_available_land.Rdata")
# 
# yard_separation <- #separates front and back yards into separate shapes
#   adu_available_land %>%
#   as_Spatial() %>%
#   sp::disaggregate() %>%
#   st_as_sf()
# 
# save(yard_setbacks, house_setback, adu_available_land, yard_separation, file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/yard_separation.Rdata")
load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/yard_separation.Rdata")
```

```{r}
# save.image(file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/test_adu_save1.Rdata")
# load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/test_adu_save1.Rdata")
```

```{r}
# This creates the merged parcel shapes, so you can know that a parcel touches a street edge if it shares an edge with the block it's part of. the buffers are first filling in some small slivers, and then producing an end block shape that is 1ft inset from the original.
# stockton_parcels_dissolve <-
#   stockton_parcels_extended %>% 
#   summarize() %>% 
#   st_buffer(1) %>% 
#   st_buffer(-2) %>%
#   as_Spatial() %>%
#   sp::disaggregate() %>%
#   st_as_sf()
# 
# save(stockton_parcels_dissolve, file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/stockton_parcels_dissolve.Rdata")
# load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/stockton_parcels_dissolve.Rdata")
# 
# This creates the clips of each parcel with the block shapes from the previous line. because of the -1ft buffer, this creates little 1ft leftover crusts.
# 
# for(row in 1:floor(nrow(stockton_parcels_dissolve)/100)){
# 
# street_edges <- NULL
# for(row in 1:floor(nrow(stockton_parcels_dissolve)/100)){
#   
#   start <- row*100-99
# 
#   end <- ifelse(
#     row < floor(nrow(stockton_parcels_dissolve)/100),
#     row*100,
#     nrow(stockton_parcels_dissolve)
#   )
# 
#   print(paste0(start," to ",end))
#   
#   street_edge <- 
#     stockton_residential_parcels[which(stockton_residential_parcels$APN %in% st_centroid(stockton_residential_parcels)[stockton_parcels_dissolve[start:end,],]$APN),] %>% 
#     mutate(
#       parcel_area = st_area(.) %>% as.numeric()
#     ) %>% 
#     st_difference(st_union(stockton_parcels_dissolve[start:end,]))
#   
#   street_edges <-
#     street_edges %>% 
#     rbind(street_edge)
#   
#   save(street_edges, file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/street_edges.Rdata")
# }
# 
# load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/street_edges.Rdata")
# 
# # Note that borders with water or green space may be incorrectly identified as street edges with this method. in EPA there are almost always buffer parcels for the baylands which prevent this from happening, but this may need to be addressed as a check on suspected throughlots using the street method, same as how the corner lot cases likely need to be sent to the street method.
# 
# # This creates a shapefile of original parcel shapes, but with the filed called "street_edges" that counts the number of distinct crusts that were created. for most normal cases, this will be 1. however note that corner lots, and parcels completely surrounded by streets, are also 1 crust. generally the expectation is that if you have more than 1 crust, you're some kind of throughlot or outlier condition.
# parcels_number_of_edges <-
#   street_edges %>% 
#   as_Spatial() %>%
#   sp::disaggregate() %>%
#   st_as_sf() %>% 
#   group_by(APN) %>% 
#   summarize(street_edges = as.numeric(n())) %>%
#   st_set_geometry(NULL) %>% 
#   left_join(stockton_parcels, by = "APN") %>% 
#   st_as_sf()
# 
# mapview(parcels_number_of_edges, zcol="street_edges")
# 
# # Reviewing the throughlot cases can lead to manual identification of false positives, but this may not be worth the time to do. for now, this sets aside all cases of 2+ crusts to be treated in a separate analysis, since you'd need to treat throughlots separately anyway.
# through_lots_or_misc <-
#   street_edges %>% 
#   as_Spatial() %>%
#   sp::disaggregate() %>%
#   st_as_sf() %>% 
#   group_by(APN) %>% 
#   summarize(count = n()) %>% 
#   filter(count > 1) %>% 
#   st_set_geometry(NULL) %>% 
#   left_join(stockton_parcels, by = "APN") %>% 
#   st_as_sf()
# 
# # This takes advantage of the convex hull operation to find bent crusts. 15% seems to be roughly the right ratio of the convex hull shape area to original parcel area to identify true corner conditions, but this will have some false positives and false negatives. these corner cases are set aside for now, likely need to be sent to the street matching script.
# corner_edges <-
#   street_edges %>%
#   filter(!APN %in% through_lots_or_misc$APN) %>% 
#   st_convex_hull() %>% 
#   mutate(
#     edge_area = st_area(.) %>% as.numeric()
#   ) %>% 
#   filter(edge_area > parcel_area*0.15)
# 
# save(street_edges, parcels_number_of_edges, through_lots_or_misc, corner_edges, file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/street_edges_analysis.Rdata")
load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/street_edges_analysis.Rdata")

# This filters to the remaining one-crust parcels that are SFR. 
normal_residential_parcels <-
  street_edges %>% 
  filter(!APN %in% through_lots_or_misc$APN) %>%
  as.data.frame() %>% 
  rename(street_edge = geometry) %>% 
  dplyr::select(APN,parcel_area,street_edge) %>% 
  left_join(stockton_parcels, by = "APN") %>%
  as.data.frame() %>% 
  rename(parcel_geometry = geometry) %>% 
  dplyr::select(APN,parcel_area,street_edge,parcel_geometry) %>% 
  right_join(residential_bldg, by = "APN") %>%
  filter(!is.na(parcel_area)) %>% 
  rename(building_geometry = WKT) %>% 
  st_as_sf()

normal_residential_parcels_distance <-
  normal_residential_parcels %>% 
  mutate(
    distance_bldg_front =
      1:nrow(normal_residential_parcels) %>% 
      map(function(row){
        if(row%%100 == 0) print(row)
        st_nearest_points(normal_residential_parcels$street_edge[row],normal_residential_parcels$building_geometry[row]) %>% 
          st_length()
      }) %>% 
      unlist()
  ) %>% 
  arrange(APN, distance_bldg_front) %>% 
  filter(!duplicated(APN))

front_yard_setback <-
  1:nrow(normal_residential_parcels_distance) %>% 
  map_dfr(function(row){
    if(row%%100 == 0) print(row)
    
    normal_residential_parcels_distance[row,] %>% 
      st_set_geometry("street_edge") %>% 
      st_buffer(normal_residential_parcels_distance$distance_bldg_front[row],joinStyle = "MITRE", mitreLimit = 1) %>% 
      as.data.frame()
  }) %>% 
  st_as_sf() %>% 
  st_set_crs(projection)

yard_separation_front_yard_setback <- NULL
for(row in 1:floor(nrow(stockton_residential_parcels)/1000)){

  start <- row*1000-999

  end <- ifelse(
    row < floor(nrow(stockton_residential_parcels)/1000),
    row*1000,
    nrow(stockton_residential_parcels)
  )

  print(paste0(start," to ",end))

  yard_separation_temp_result <-
    yard_separation[which(yard_separation$APN %in% stockton_residential_parcels$APN[start:end]),]
  
  front_yard_setback_temp_result <-
    front_yard_setback[which(front_yard_setback$APN %in% stockton_residential_parcels$APN[start:end]),] %>% 
    st_union()

  yard_separation_front_yard_setback <-
    yard_separation_front_yard_setback %>%
    rbind(
      st_difference(
        yard_separation_temp_result,
        front_yard_setback_temp_result
      )
    )
}

yard_separation_front_yard_setback <-
  yard_separation_front_yard_setback %>% 
  mutate(
    yard_area = st_area(.) %>% as.numeric()
  ) %>% 
  filter(yard_area >= 160)

normal_residential_parcels_yards <-
  normal_residential_parcels_distance %>%
  as.data.frame() %>%
  right_join(yard_separation_front_yard_setback %>% dplyr::select(APN,yard_area), by = "APN") %>% 
  filter(!is.na(parcel_area)) %>% 
  rename(yard_geometry = geometry) %>% 
  st_set_geometry("yard_geometry")

mapview(normal_residential_parcels_yards[1:100,] %>% st_set_geometry("parcel_geometry"),alpha.region=0)+mapview(normal_residential_parcels_yards[1:100,] %>% st_set_geometry("street_edge")) + mapview(normal_residential_parcels_yards[1:100,] %>% st_set_geometry("yard_geometry")) + mapview(normal_residential_parcels_yards[1:100,] %>% st_set_geometry("building_geometry"))
```

```{r}
# save.image(file = "C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/test_adu_save2.Rdata")
# load("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/test_adu_save2.Rdata")
```

```{r}
# Takes two points and calculates the slope between them. Reference 0 degrees would be due east, and positive degrees are in the clockwise direction.
get_angle <- function(pt1,pt2){
  angle <- atan2((pt2[2]-pt1[2]),(pt2[1]-pt1[1]))
  return(angle)
}

# this creates a rotation matrix that can be multiplied by a point to get a point rotated counter-clockwise relative to (0,0). I found this online. Since my get_angle function gives degrees in the clockwise direction, it'd be great to reverse this rot function, but I didn't bother to figure out the math -- just added a negative in get_adu below.
rot <- function(a) matrix(c(cos(a), sin(a), -sin(a), cos(a)), 2, 2)

get_adu_forward <- function(centroid,width,length,angle){
  # this is revised ADU, the 8x20 is shifted 6ft to the right before rotating, which might do better fitting at corners.
  corner1 <- st_point(centroid)+st_point(c(-width/2,-width/2))*rot(-angle) 
  corner2 <- st_point(centroid)+st_point(c(length-width/2,-width/2))*rot(-angle) 
  corner3 <- st_point(centroid)+st_point(c(length-width/2,width/2))*rot(-angle) 
  corner4 <- st_point(centroid)+st_point(c(-width/2,width/2))*rot(-angle) 
  
  
  adu <- 
    rbind(corner1,corner2,corner3,corner4,corner1) %>%
    list() %>% 
    st_polygon() %>% 
    st_sfc() %>% 
    st_sf() %>% 
    st_set_crs(projection)
  
  return(adu)
}

get_adu_sideways_counterclockwise <- function(centroid,width,length,angle){
  # this is a second revised ADU, the 8x20 is rotated 90 degrees relative to the previous one, so the ADU is sticking further into the inside of the yard area, which might do better fitting in certain areas that were previously unexplored.
  corner1 <- st_point(centroid)+st_point(c(-width/2,-width/2))*rot(-angle) 
  corner2 <- st_point(centroid)+st_point(c(width/2,-width/2))*rot(-angle) 
  corner3 <- st_point(centroid)+st_point(c(width/2,length-width/2))*rot(-angle) 
  corner4 <- st_point(centroid)+st_point(c(-width/2,length-width/2))*rot(-angle) 
  
  
  adu <- 
    rbind(corner1,corner2,corner3,corner4,corner1) %>%
    list() %>% 
    st_polygon() %>% 
    st_sfc() %>% 
    st_sf() %>% 
    st_set_crs(projection)
  
  return(adu)
}

# DO: note there was a typo in this (formerly adu3.5), the math for corners 3 and 4
get_adu_sideways_clockwise <- function(centroid,width,length,angle){
  # this is the same as get_adu2 but mirrored, since depending on which way you're going around the track clockwise or counterclockwise you might be sticking inwards or outwards. (I haven't checked if it's always a certain direction, maybe it is and you can definitely know which of these functions is the one to use. In my test case go[5048,], get_adu3 was the correct one, and the track was going clockwise)
  corner1 <- st_point(centroid)+st_point(c(width/2,width/2))*rot(-angle) 
  corner2 <- st_point(centroid)+st_point(c(-width/2,width/2))*rot(-angle) 
  corner3 <- st_point(centroid)+st_point(c(-width/2,-length+width/2))*rot(-angle) 
  corner4 <- st_point(centroid)+st_point(c(width/2,-length+width/2))*rot(-angle) 
  
  adu <- 
    rbind(corner1,corner2,corner3,corner4,corner1) %>%
    list() %>% 
    st_polygon() %>% 
    st_sfc() %>% 
    st_sf() %>% 
    st_set_crs(projection)
  
  return(adu)
}
```

```{r}
length <- 20
width <- 8
increment <- 2

sspz <- st_read("C:/Users/Derek Ouyang Ouyang/Google Drive/City Systems/Stockton Green Economy/sspzboundary/sspzboundary.shp") %>% 
  st_transform(projection)

sspz_parcels <- normal_residential_parcels_yards[which(normal_residential_parcels_yards$APN %in% st_centroid(normal_residential_parcels_yards)[sspz,]$APN),]

non_sspz_parcels <-
  normal_residential_parcels_yards %>% 
  filter(!APN %in% sspz_parcels$APN)

go <- rbind(
  sspz_parcels,
  non_sspz_parcels
) %>% 
  st_set_geometry("yard_geometry")
  

go <- normal_residential_parcels_yards

go_buffer <- 
  go %>% 
  st_buffer(-width/2-0.25,joinStyle="MITRE",mitreLimit=1)

# counter for cases where churro fails
churro_fail <- NULL

go_collected_buildable_area <- NULL
for(parcelRow in 1:nrow(go)){
  
  print(parcelRow)
  cbuffer <- go[parcelRow,]
  go_adus <- NULL
  
  parcel_coords <-
    go_buffer[parcelRow,] %>%
    st_coordinates()
  
  start <- proc.time()
  
  if(is_empty(parcel_coords)){
    parcel_coords <- NULL
  } else{
    
    for(point in 1:(nrow(parcel_coords)-1)){
      
      # print(point)
      pt1 <- parcel_coords[point,1:2]
      pt2 <- parcel_coords[point+1,1:2]
      
      line <-
        rbind(pt1,pt2) %>%
        st_linestring() %>%
        st_sfc() %>%
        st_sf() %>%
        st_set_crs(projection)

      go_angle <- get_angle(pt1,pt2)
      
      segments <- 
        line %>% 
        st_segmentize(increment) %>% 
        st_coordinates()
      
      # try making increment dynamic
      # forward/backward direction
      segment <- 1
      first_forward_eligible_adu <- NULL
      while(is.null(first_forward_eligible_adu) & segment <= nrow(segments)){
        adu_candidate <- 
          get_adu_forward(segments[segment,1:2],width,length,go_angle) %>% 
          filter(st_covers(cbuffer,.,sparse=F))
        if(nrow(adu_candidate) > 0) first_forward_eligible_adu <- adu_candidate
        segment <- segment + 1
      }
      
      #simple backwards check if forwards completely fails, just checking "behind" the forward track
      last_forward_eligible_adu <- NULL
      if(is.null(first_forward_eligible_adu)){
        for(segment in pmin(nrow(segments),(length-width/2)/increment):1){
          adu_candidate <- 
            get_adu_forward(segments[segment,1:2],width,length,go_angle + pi) %>% 
            filter(st_covers(cbuffer,.,sparse=F))
          if(nrow(adu_candidate) > 0) last_forward_eligible_adu <- adu_candidate
        }
      }
      
      segment <- 1
      first_sideways_eligible_adu <- NULL
      while(is.null(first_sideways_eligible_adu) & segment <= nrow(segments)){
        adu_candidate <- 
          get_adu_sideways_clockwise(segments[segment,1:2],width,length,go_angle) %>% 
          filter(st_covers(cbuffer,.,sparse=F))
        if(nrow(adu_candidate) > 0) first_sideways_eligible_adu <- adu_candidate
        segment <- segment + 1
      }
      
      last_sideways_eligible_adu <- NULL
      if(is.null(first_sideways_eligible_adu)){
        for(segment in pmin(nrow(segments),(length-width/2)/increment):1){
          adu_candidate <- 
            get_adu_sideways_counterclockwise(segments[segment,1:2],width,length,go_angle + pi) %>% 
            filter(st_covers(cbuffer,.,sparse=F))
          if(nrow(adu_candidate) > 0) last_sideways_eligible_adu <- adu_candidate
        }
      }
      
      # if no eligible ADU, next
      if(is.null(first_forward_eligible_adu) & 
         is.null(last_forward_eligible_adu) &
         is.null(first_sideways_eligible_adu) &
         is.null(last_sideways_eligible_adu)) next
      
      forward_churro <- NULL
      sideways_churro <- NULL
      
      # finish checking forward_adu
        
      segment <- nrow(segments)
      last_forward_eligible_adu <- NULL
      while(is.null(last_forward_eligible_adu) & segment > 0){
        adu_candidate <- 
          get_adu_forward(segments[segment,1:2],width,length,go_angle + pi) %>% 
          filter(st_covers(cbuffer,.,sparse=F))
        if(nrow(adu_candidate) > 0) last_forward_eligible_adu <- adu_candidate
        segment <- segment - 1
      }
      
      if(!is.null(last_forward_eligible_adu)){
        forward_churro <- 
          rbind(first_forward_eligible_adu, last_forward_eligible_adu) %>% 
          summarise() %>% 
          st_convex_hull() %>% 
          filter(st_covers(cbuffer,.,sparse=F))
        
        # if churro fails
        if(nrow(forward_churro)==0){
          churro_fail <-
            churro_fail %>% 
            rbind(forward_churro) %>%
            mutate(parcelRow = parcelRow)
          
          forward_churro <- NULL
          for(segment in 1:nrow(segments)){
            forward_churro <- 
              forward_churro %>% 
              rbind(
                get_adu_forward(segments[segment,1:2],width,length,go_angle) %>% 
                filter(st_covers(cbuffer,.,sparse=F))
              )
          }
          for(segment in nrow(segments):1){
            forward_churro <- 
              forward_churro %>% 
              rbind(
                get_adu_forward(segments[segment,1:2],width,length,go_angle+pi) %>% 
                filter(st_covers(cbuffer,.,sparse=F))
              )
          }
          forward_churro <- forward_churro %>% summarise()
        }
      }
      
      # finish checking sideways adu
        
      segment <- nrow(segments)
      last_sideways_eligible_adu <- NULL
      while(is.null(last_sideways_eligible_adu) & segment > 0){
        adu_candidate <- 
          get_adu_sideways_counterclockwise(segments[segment,1:2],width,length,go_angle + pi) %>% 
          filter(st_covers(cbuffer,.,sparse=F))
        if(nrow(adu_candidate) > 0) last_sideways_eligible_adu <- adu_candidate
        segment <- segment - 1
      }
      
      if(!is.null(last_sideways_eligible_adu)){
        
        sideways_churro <- 
          rbind(first_sideways_eligible_adu, last_sideways_eligible_adu) %>% 
          summarise() %>% 
          st_convex_hull() %>% 
          filter(st_covers(cbuffer,.,sparse=F))
        
        # if churro fails
        if(nrow(sideways_churro)==0){
          churro_fail <-
            churro_fail %>% 
            rbind(sideways_churro) %>%
            mutate(parcelRow = parcelRow)
          
          sideways_churro <- NULL
          for(segment in 1:nrow(segments)){
            sideways_churro <- 
              sideways_churro %>% 
              rbind(
                get_adu_sideways_clockwise(segments[segment,1:2],width,length,go_angle) %>% 
                filter(st_covers(cbuffer,.,sparse=F))
              )
          }
          for(segment in nrow(segments):1){
            sideways_churro <- 
              sideways_churro %>% 
              rbind(
                get_adu_sideways_counterclockwise(segments[segment,1:2],width,length,go_angle+pi) %>% 
                filter(st_covers(cbuffer,.,sparse=F))
              )
          }
          sideways_churro <- sideways_churro %>% summarise()
        }
        
      }
      
      go_adus <-
        go_adus %>% 
        rbind(
          forward_churro,
          sideways_churro
        )
    }
  }
    
  if(is.null(go_adus) | is.null(parcel_coords)){
    go_adus_merge <-
      st_sf(st_sfc(st_multipolygon())) %>% 
        mutate(
          APN = go$APN[parcelRow],
          parcelRow = parcelRow,
          compute_time = proc.time()[3] - start[3]
        ) %>% 
      rename(geometry = st_sfc.st_multipolygon...) %>% 
      st_set_crs(projection)
  } else {
    go_adus_merge <-
      go_adus %>%
        st_make_valid() %>% 
        st_buffer(0.1) %>% 
        st_buffer(-0.1) %>% 
        summarise() %>% # can throw a self-intersection error
        mutate(
          APN = go$APN[parcelRow],
          parcelRow = parcelRow,
          compute_time = proc.time()[3] - start[3]
        )
  }
  
  go_collected_buildable_area <- 
    go_collected_buildable_area %>%
    rbind(
      go_adus_merge
    )
  
  # if(parcelRow%%1000 == 0) save(go_collected_buildable_area, file = "C:/Users/Derek Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/go_collected_buildable_area.Rdata")
}
```

```{r}
# save(go_collected_buildable_area, file = "C:/Users/Derek Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/go_collected_buildable_area.Rdata")
# load("C:/Users/Derek Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/go_collected_buildable_area.Rdata")
```

```{r}
clean_buildable_area <-
  go_collected_buildable_area %>% 
  filter(!st_is_empty(.)) %>% 
  st_buffer(2) %>% 
  st_buffer(-2) %>% 
  fill_holes(threshold = units::set_units(100000000, ft^2)) %>% 
  as_Spatial() %>% 
  sp::disaggregate() %>% 
  st_as_sf() %>% 
  mutate(
    yard_area = st_area(.) %>% as.numeric()
  ) %>% 
  arrange(APN,desc(yard_area)) %>% 
  filter(!duplicated(APN)) %>% 
  mutate(
    buildable_area = floor(yard_area/10)*10
  )

save(clean_buildable_area,normal_residential_parcels_yards,file="C:/Users/Derek Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/clean_buildable_area.Rdata")
```

```{r}
# save.image(file = "C:/Users/Derek Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/test_adu_save3.Rdata")
# load("C:/Users/Derek Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/test_adu_save3.Rdata")
```

focus on sspz
```{r}
sspz_buildable_area <-
  clean_buildable_area %>% 
  filter(APN %in% sspz_parcels$APN)

# mapview(sspz_buildable_area)

sspz_buildable_area_filtered <-
  sspz_buildable_area %>% 
  filter(buildable_area < 15000)
```

```{r}
rtd_gtfs <- read_gtfs("http://sjrtd.com/RTD-GTFS/RTD-GTFS.zip")
rtd_stops <- 
  st_as_sf(rtd_gtfs$stops,coords=c(6,5)) %>% 
  st_set_crs(4326) %>% 
  st_transform(projection)

sspz_rtd_stops <-
  rtd_stops[sspz,]

rtd_stops_downtownstation <-
  c("7258","7017","7155","7003","7006","7025")

rtd_stops_amtrak <-
  c("7029","7032")

# walk_times <- 
#   data.frame(
#     stop_id = c(rtd_stops_downtownstation, rtd_stops_amtrak),
#     walk_time = c(rep(600, 8)), 
#     stringsAsFactors = F
#   )

start_hour <- 16
end_hour <- 20
max_time_minutes <- 15

stop_times <- filter_stop_times(rtd_gtfs, "2020-02-24", start_hour*3600, end_hour*3600)

stop_frequency <-
  get_stop_frequency(
    rtd_gtfs,
    start_hour,
    end_hour
  )

rptr <- 
  raptor(
    stop_times, 
    rtd_gtfs$transfers, 
    rtd_stops_downtownstation, 
    departure_time_range = (end_hour-start_hour)*3600,
    keep = "shortest"
  )

downtown_accessible_stops <-
  rptr %>% 
  mutate(
    travel_time_minutes = (min_arrival_time-journey_departure_time)/60,
    walking_time_minutes = max_time_minutes - travel_time_minutes
  ) %>% 
  filter(travel_time_minutes <= max_time_minutes) %>% 
  left_join(rtd_stops, by = "stop_id") %>% 
  st_as_sf() %>% 
  left_join(stop_frequency, by = "stop_id") %>% 
  filter(departures >= (end_hour-start_hour)*4)

downtown_accessible_zone <-
  1:nrow(downtown_accessible_stops) %>% 
  map_dfr(function(row){
    downtown_accessible_stops[row,] %>% 
      st_buffer(downtown_accessible_stops$walking_time_minutes[row]/20*5280) %>% # convert minutes to ft assuming 20 minutes per mile walking
      as.data.frame()
  }) %>% 
  st_as_sf() %>% 
  st_set_crs(projection)

# downtown_accessible_sspz_adus <-
#   sspz_buildable_area_filtered[which(sspz_buildable_area_filtered$APN %in% st_centroid(sspz_buildable_area_filtered)[downtown_accessible_zone,]$APN),]

downtown_accessible_adus <-
  clean_buildable_area[which(clean_buildable_area$APN %in% st_centroid(clean_buildable_area)[downtown_accessible_zone,]$APN),]

downtown_accessible_adus_filtered <-
  downtown_accessible_adus %>% 
  filter(buildable_area < 15000)

routes <- 
  get_route_geometry(
    rtd_gtfs %>% gtfs_as_sf(), 
    route_ids = downtown_accessible_stops$route_id,
    service_ids = downtown_accessible_stops$service_id
  ) %>% 
  st_transform(projection) #%>% 
  # st_intersection(sspz)

# routes <-
#   1:nrow(routes) %>% 
#   map_dfr(function(row){
#     connecting_line <- st_nearest_points(downtown_accessible_stops[which(downtown_accessible_stops$route_id == routes$route_id[row]),],routes[which()])
#     st_intersection(st_union(downtown_accessible_zone) %>% st_convex_hull())
#   })

mapview(downtown_accessible_stops, layer.name= "Bus Stops")+
  mapview(downtown_accessible_stops %>% filter(stop_id %in% rtd_stops_downtownstation), cex = 10, col.regions = "red", layer.name = "Downtown Bus Station") +
  mapview(routes$geometry, layer.name = "Bus Routes") +
  mapview(downtown_accessible_adus_filtered, col.regions = "green", lwd=0.5, layer.name= "Buildable ADU Area")

# leaflet() %>% 
#   addMapPane("test_back", zIndex = 2) %>% 
#   addMapPane("test_front", zIndex = 1)
# 
# mapview(sspz, alpha.region=0, legend = FALSE) +
#   mapview(downtown_accessible_sspz_adus, col.regions = "green", lwd=0.5, layer.name= "Buildable ADU Area")

  # mapview(normal_residential_parcels %>% st_set_geometry("parcel_geometry") %>% filter(APN %in% downtown_accessible_sspz_adus$APN), alpha.region=0, color = "white", layer.name= "Parcels") +
```

```{r}
# save.image(file = "C:/Users/Derek Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/test_adu_save4.Rdata")
# load("C:/Users/Derek Ouyang/Google Drive/City Systems/Stockton Green Economy/ADU/test_adu_save4.Rdata")
```